### ISSUE TITLE
PHP8.2

### ISSUE THREAD

**Issue by joshbmarshall** [square/square-php-sdk#102]
Hi I have an application that requires PHP8.2
Can this work with PHP8.2?

**Comment by havenwood** [comment]
PHP 8.2 support is on our radar but the SDK is unfortunately currently limited to PHP 8.1. Thank you for the ping!

**Comment by haszari** [comment]
> PHP 8.2 support is on our radar but the SDK is unfortunately currently limited to PHP 8.1. Thank you for the ping!

To clarify, @havenwood are there specific issues or risks with using the PHP SDK on PHP 8.2? [WooCommerce supports PHP 7.2 (with no upper limit)](https://github.com/woocommerce/woocommerce), and the [WooCommerce Square extension](https://woocommerce.com/products/square/) uses the Square SDK. 

WooCommerce merchants will be using a variety of PHP versions and if there's any real risks or issues we need to understand and document this to prevent impact on stores/functionality.

**Comment by joshbmarshall** [comment]
I can confirm that switching the hosting to PHP8.2 after installing with composer on PHP8.1, the square sdk continues to work perfectly for me taking payments.

From what I see it just needs the composer limitation removed.

**Comment by havenwood** [comment]
> > PHP 8.2 support is on our radar but the SDK is unfortunately currently limited to PHP 8.1. Thank you for the ping!
> 
> To clarify, @havenwood are there specific issues or risks with using the PHP SDK on PHP 8.2? [WooCommerce supports PHP 7.2 (with no upper limit)](https://github.com/woocommerce/woocommerce), and the [WooCommerce Square extension](https://woocommerce.com/products/square/) uses the Square SDK.
> 
> WooCommerce merchants will be using a variety of PHP versions and if there's any real risks or issues we need to understand and document this to prevent impact on stores/functionality.

@haszari PHP 8.2 is now supported. The upstream issue causing installation issues has been resolved. There are no known issues with PHP 8.2 and the README will reflect support with the next Square SDK release.

@joshbmarshall thank you for your initial bug report and follow up! We prioritized fixing the issue after your report. I apologize for our delay in supporting the latest stable version of PHP.

I'll close this issue now that PHP 8.2 is officially supported and documentation will shortly follow. Thank you!

**Comment by joshbmarshall** [comment]
> when this package will be upgraded for 8.2 or 8.3 version

I've been using this package on PHP 8.3 for many months now...
