### ISSUE TITLE
difference in api explorer and sdk for creating a device code with product type set

### ISSUE THREAD

**Issue by dunkoh** [square/square-php-sdk#104]
**Describe the bug**
In API explorer for API version 2023-01-19 it has it passing the product_type into the DeviceCode class
```
$device_code = new \Square\Models\DeviceCode('TERMINAL_API');
```
In SDK version 25.1.0.20230119 it isn't setup to accept the product_type in the construct of the class since there isn't one.

Is this an API Explorer bug/typo and should we pass in the product type instead?
```
$device_code = new \Square\Models\DeviceCode();
$device_code->setProductType('TERMINAL_API');
```

**Comment by zenmasterjobo** [comment]
hi @dunkoh,

We are currently investigating an issue with our SDK which has caused some divergence between API Explorer examples for php, and what the SDK supports.

Ideally, all required params on a model should be available to set in the object's constructor. Until we get this issue resolved, setting the product type as you are in your last example is the correct work around.

**Comment by zenmasterjobo** [comment]
The API Explorer example code has been updated and fixed to reflect how this field should be set
