### ISSUE TITLE
"failed to open stream: No such file or directory" in error in JsonMapper.php file.

### ISSUE THREAD

**Issue by iamdharmesh** [square/square-php-sdk#111]
**Describe the bug**
We are using this Square SDK on the WooCommece-Square plugin and the below error is faced by some of our customers. 
```
[07-Dec-2022 17:03:15 UTC] PHP Warning:  parse_ini_file(/usr/local/php7.4/conf/php.ini): failed to open stream: No such file or directory in /srv/htdocs/wp-content/plugins/woocommerce-square/vendor/apimatic/jsonmapper/src/JsonMapper.php on line 119
```

This is happening because certain hosting services don't allow to access resources outside the `public` directory due to security reasons, which is something a dependency of the Square SDK (JsonMapper) tries to do.

I noticed that the JsonMapper repo also has reported an issue for the same here https://github.com/apimatic/jsonmapper/issues/28. We may check if it gets resolved there OR maybe we can look for an alternative for JsonMapper to get rid of this and make it possible to use Square SDK on all hosting providers.

**Expected behavior**
Square SDK should work without any errors.

**To Reproduce**
Steps to reproduce the bug:
Initialize the Square Client and try to call Square API. As this error comes on several hosting providers only it is unlikely that you will get it to reproduce locally directly. Please let me know if you need any further information on reproduce issue.
Based on information from customers, they are experiencing this error on **Pressable** and **Kinsta** hosting provider

**Screenshots**
If applicable, add screenshots to help explain the bug.

**Square SDK version**
24.0.0.20221116

**Additional context**
A similar issue reported earlier https://github.com/square/square-php-sdk/issues/87

Reference issues in woocommerce-square repo
https://github.com/woocommerce/woocommerce-square/issues/924
https://github.com/woocommerce/woocommerce-square/issues/990

**Comment by iamdharmesh** [comment]
@jessdelacruzsantos This issue has been addressed and resolved in the recent release of JsonMapper. Maybe the best time to fix it here by updating the dependency version here in square SDK?

**Comment by zenmasterjobo** [comment]
hi @iamdharmesh 

These changes should be brought in and reflect in our July release. Currently we scheduling for that to go live July 6th. 

Thanks again for your contributions in highlighting this issue!

**Comment by iamdharmesh** [comment]
Thank you @zenmasterjobo, this is fixed in the latest version of SDK.
