### ISSUE TITLE
Now getCheckoutPageUrl() returning a Reletive Path

### ISSUE THREAD

**Issue by atharalipk** [square/square-php-sdk#123]
Due to the last update now we are getting the Reletive path for checkout page where it was absolute I think you have to mention this change anywhere and the changelog link is not working
https://developer.squareup.com/docs/changelog/connect-logs/2023-09-25

I think this should be absolute path

**Comment by zenmasterjobo** [comment]
HI @atharalipk 

Can you clarify what you clarify what you mean? Is this in the response data, or how you include the SDK into your project?

**Comment by atharalipk** [comment]
Hi @zenmasterjobo

yes that is response from createCheckout when the buyesr's browser should be redirected to after the checkout is completed

$response->getResult()->getCheckout()->getCheckoutPageUrl()

the above response is now fixed returning absolute path
last day I was getting this in response (Relative Path)
/v2/checkout?c=ABCDEFGHI232323WDR&l=QWERTDFXEB
Now it is fixed and getting (absolute path)
https://connect.squareup.com/v2/checkout?c=ABCDEFGHI232323WDR&l=QWERTDFXEB

**Comment by zenmasterjobo** [comment]
Ah ok, yeah must have been a change on the API side, I apologize that we didn't have that change documented - but since it's now back to the 'absolute path' I assume that change was unintentional.

Thanks for raising the problem, and glad it's fixed. Feel free to reopen if the problem persists
