### ISSUE TITLE
`InvalidArgumentException: Invalid Url format.` when using any custom server URL

### ISSUE THREAD

**Issue by Rhys-T** [square/square-php-sdk#130]
**Describe the bug**
If I set the `SquareClient`'s `environment` to `\Square\Environment::CUSTOM`, no matter what `customUrl` I pass, the underlying Apimatic libraries throw `InvalidArgumentException: Invalid Url format.`

[The Square SDK is passing `'{custom_url}'` into the Apimatic `ClientBuilder`](https://github.com/square/square-php-sdk/blob/c60d39ae3d53e244a7f7c31a0fda136b250b9bd9/src/SquareClient.php#L802C53-L802C67), presumably expecting it to be substituted in from the other settings being passed in. But by patching Apimatic's `validateUrl` function to print out the URL it's getting, I was able to determine that the `'{custom_url}'` string is being used as-is.

<details>
<summary>Example stack trace</summary>

```
Fatal error:  Uncaught InvalidArgumentException: Invalid Url format. in /path/to/my/site/vendor/apimatic/core/src/Utils/CoreHelper.php:56
Stack trace:
#0 /path/to/my/site/vendor/apimatic/core/src/Request/Request.php(34): Core\Utils\CoreHelper::validateUrl()
#1 /path/to/my/site/vendor/apimatic/core/src/Client.php(90): Core\Request\Request->__construct()
#2 /path/to/my/site/vendor/apimatic/core/src/Request/RequestBuilder.php(138): Core\Client->getGlobalRequest()
#3 /path/to/my/site/vendor/apimatic/core/src/ApiCall.php(45): Core\Request\RequestBuilder->build()
#4 /path/to/my/site/vendor/square/square/src/Apis/BaseApi.php(34): Core\ApiCall->execute()
#5 /path/to/my/site/vendor/square/square/src/Apis/PaymentsApi.php(121): Square\Apis\BaseApi->execute()
#6 /path/to/my/site/someScript.php(90): Square\Apis\PaymentsApi->createPayment()
#7 {main}
  thrown in /path/to/my/site/vendor/apimatic/core/src/Utils/CoreHelper.php on line 56
```

</details>

**Expected behavior**
The Square SDK should successfully connect to a custom server URL (or fail with a different error message if it can't get to that server).

**To Reproduce**
Steps to reproduce the bug:
1. Start with a basic script that can talk to the Square sandbox environment, for example the one from [the quickstart](https://developer.squareup.com/docs/sdks/php/quick-start).
2. Change the `SquareClient`'s `environment` parameter from `SANDBOX` to `CUSTOM`.
3. Add a `customUrl` parameter, and set it to `https://connect.squareupsandbox.com`.
4. Try running the script. It should work exactly the same as on `SANDBOX`, but instead it throws the `Invalid Url format` error.

**Square SDK version**
34.0.1.20240118

**Additional context**
I'm not actually trying to use a custom Square server. I was originally trying to set the custom URL to `https://connect.squareupsandbox.invalid`, to test how my code handles errors when trying to reach Square's servers. That _would_ be an 'invalid URL', but not an invalid _format_ - and when I tried it with the `https://connect.squareupsandbox.com` URL copied straight out of `SquareClient`'s own code, it failed exactly the same way.

**Comment by zenmasterjobo** [comment]
hi @Rhys-T 

just wanted to confirm that updating the square-php sdk and it's dependencies to version `35.0.0.20240222` has fixed the issue for me. Please update and let me know if you still run into issues!
