### ISSUE TITLE
getShippingAddress() Method in Payment Model returns NULL

### ISSUE THREAD

**Issue by Hackinet** [square/square-php-sdk#19]
I create a checkout Object and put `setAskForShippingAddress()` to `true`, and it does indeed collect shipping address during the hosted checkout. 

However, the API Docs do not specify as to how to fetch that back. The `$api_response = $client->getCheckoutApi()->createCheckout('$location_id', $checkout_data_body)` does not return it. Your `payment.updated` webhook does not send back the shipping address either on payment completion (I do however get the payment_id and order_id, but neither the Payment or Order API contain the shipping address).

How do get the shipping address filled by customer during the hosted checkout?

**UPDATE**

I was going through the Models and the `Payment `model does have a method but it returns `NULL`. This is the `var_dump()` snippet of `$apiResponse = $paymentsApi->getPayment($paymentId)`: 

```
      ["referenceId":"Square\Models\Payment":private]=>
      NULL
      ["customerId":"Square\Models\Payment":private]=>
      NULL
      ["employeeId":"Square\Models\Payment":private]=>
      NULL
      ["refundIds":"Square\Models\Payment":private]=>
      NULL
      ["buyerEmailAddress":"Square\Models\Payment":private]=>
      NULL
      ["billingAddress":"Square\Models\Payment":private]=>
      NULL
      ["shippingAddress":"Square\Models\Payment":private]=>
```

This is still an issue. Help.

**Comment by StephenJosey** [comment]
When using the Checkout API, the shipping address will be added to the customer's address, not part of the payment/order. You can retrieve the payment and get the `customer_id`, and retrieve the customer using RetrieveCustomer, and the address should be there. Let me know if you find that to not be true, or if you have further questions.

**Comment by sseaman** [comment]
Closing as no additional questions posted.  Please feel free to reopen if you need to.
