### ISSUE TITLE
Fatal error: Uncaught Error: Cannot access private property Square\Models\Location::$id

### ISSUE THREAD

**Issue by umaraliyar** [square/square-php-sdk#20]
Hi,
After updating SDK using composer, I am getting 
"Fatal error: Uncaught Error: Cannot access private property Square\Models\Location::$id" in Line 26,
when I tried printing a Locations ID as,
**print_r($location->id);** instead of **print_r($location);**
I am using first API for Square example from,
https://github.com/umaraliyar/square-php-sdk

It was working as expected when I use "6.0.0.20200625"

I am not getting a clue what I am missing.

**Comment by StephenJosey** [comment]
The fields are protected, so you'll need to use the setter `$location->getId()`. Let me know if that doesn't work, though!

**Comment by umaraliyar** [comment]
It works thanks!
