### ISSUE TITLE
I want to Integrate Squire up api in my php Codeigniter to retrieve all Inventory into my system

### ISSUE THREAD

**Issue by ratansinghgit** [square/square-php-sdk#27]
I want to Fetch All Item into my PHP web app,  and I am new to squire up so please guide me how can I do that
https://prnt.sc/uvwe7w

Thanks

**Comment by ratansinghgit** [comment]
How can I get Adjustment_id Please guide me

**Comment by ratansinghgit** [comment]
> How can I get Adjustment_id Please guide me

**Comment by StephenJosey** [comment]
If you retrieve the changes (https://developer.squareup.com/reference/square/inventory-api/batch-retrieve-inventory-changes), then you will get ids like `adjustment_id`.

**Comment by havenwood** [comment]
@ratansinghgit Hi! If you have any more questions, please join us in the [Square Developer Forums](https://developer.squareup.com/forums/) or [Square Developer Slack](http://squ.re/slack) and we'd be happy to help.
