### ISSUE TITLE
Uncaught Error: Class 'SquareClient' not found 

### ISSUE THREAD

**Issue by Swapnilchavan18** [square/square-php-sdk#3]
I started on working with new php sdk and it gives me an error. I checked code inside sdk and there is no class 'SquareClient', but other classes(LocationsApi,Environment) are found. What I am doing wrong? Is this sdk production ready?

```
require_once "square_sdk/vendor/autoload.php";
use Square\SquareClient;
$sq_client = new SquareClient([
	'accessToken' => $square_access_token,
	'environment' => Environment::SANDBOX,
]);
```

**Comment by StephenJosey** [comment]
The class definitely exists: https://github.com/square/square-php-sdk/blob/master/src/SquareClient.php. When I install via composer, it finds the SquareClient successfully. Are you saying in your repo you downloaded, you do not see this file (`SquareClient.php`)?

**Comment by Swapnilchavan18** [comment]
I installed it via composer. Using in CI. File exists but use Square\SquareClient gives error while others  Square\LocationsApi don't give any error

**Comment by vhovarfb** [comment]
@Swapnilchavan18 I have had an issue since trying to download and use the new SDK. I use Option 3 which is to download the zip file and unzip it on my webserver (Bluehost). I then point to the location as I have with all the previous, Square Connect, SDKs. The problem I'm having is that there isn't an autoload.php provided in the download so my code fails straight away when trying to do the require for the autoload.php. Can I ask how you got around that issue?

**Comment by sseaman** [comment]
Closing due to lack of response.  Please feel free to open again if you would like to continue the conversation.

**Comment by Swapnilchavan18** [comment]
Error was with php 7.0. It works perfectly with php 7.4.

**Comment by itsmemanoj** [comment]
@Swapnilchavan18  what about 7.2?
i am having the same issue.

**Comment by Swapnilchavan18** [comment]
I directly migrated from 7.0 to 7.4 , but as readme says minimum requirement of PHP 7.1+, so php 7.2 should be ok. Are you using with composer?

**Comment by itsmemanoj** [comment]
Yes, i am using composer.
It worked now.
Don't know what was the problem but I completely removed the vendor
directory and downloaded square again then it worked fine.
not sure why the `composer update` didn't work.
