### ISSUE TITLE
Could not find required constructor arguments for "\\Square\\Models\\AdditionalRecipient: description"

### ISSUE THREAD

**Issue by tabirkeland** [square/square-php-sdk#36]
API version: `2021-01-21`
SDK version: `8.1.0.20210121`

`JsonMapperException` is thrown when calling `OrdersApi::searchOrders`.

This is due to the fact that the `description` attribute on `Models\AdditionalRecipient` is required.

This field _should_ be optional/nullable.

Example:
```
{
    "additional_recipients": [{"location_id": "XXXXXXXXXX","amount_money": {"amount": 10,"currency": "USD"},"receivable_id": "XXXXXXXXXX"}]
}
```

**Comment by hukid** [comment]
@tabirkeland this is breaking change made to the AdditionalRecipient recently where we change it to be nullable. The newer version (`>9.1`) has fixed it. Can you please upgrade to the new version of SDK?

**Comment by tabirkeland** [comment]
@hukid Understood.  I have updated to `>9.1`
