### ISSUE TITLE
Missing class \Square\Models\CompletePaymentRequest

### ISSUE THREAD

**Issue by simplimation** [square/square-php-sdk#37]
The model referenced in API docs for capturing an payment is missing. https://developer.squareup.com/explorer/square/payments-api/complete-payment

**Comment by StephenJosey** [comment]
Thanks, I will make sure the API Explorer is updated. This model is not actually required, it only needs to pass the `payment_id` to the `CompletePayment` request.

**Comment by simplimation** [comment]
I may be missing something, but there's no CompletePayment request model object in the SDK.

**Comment by StephenJosey** [comment]
Right, sorry I should've been more explicit: the model does not exist, and it is not needed so it will not be created. You can simply call the `CompletePayment` endpoint like so:

```
$apiResponse = $paymentsApi->completePayment($paymentId);
```
https://github.com/square/square-php-sdk/blob/master/doc/apis/payments.md#complete-payment
