### ISSUE TITLE
Missing CompletePayment model

### ISSUE THREAD

**Issue by simplimation** [square/square-php-sdk#38]
I may be missing something, but there's no CompletePayment request model object in the SDK.

_Originally posted by @simplimation in https://github.com/square/square-php-sdk/issues/37#issuecomment-786066405_

**Comment by StephenJosey** [comment]
See: https://github.com/square/square-php-sdk/issues/37#issuecomment-786066405. It does not exist, and will not be created. The model is not required. We will work to update the API Explorer to remove incorrect references to the model that doesn't exist.
