### ISSUE TITLE
SquareClient.php throwing an uncaught exception (type string expected, null received)

### ISSUE THREAD

**Issue by rsleventhal** [square/square-php-sdk#4]
In my development environment, I'm testing the new PHP SDK before going live.

I'm in the Environment::SANDBOX for sure but getting this error:

`[15-Jun-2020 13:03:07 America/New_York] PHP Notice:  Undefined index: Environment::SANDBOX, in /path/to/vendor/square/square/src/SquareClient.php on line 139
[15-Jun-2020 13:03:07 America/New_York] PHP Fatal error:  Uncaught TypeError: Return value of Square\SquareClient::getBaseUri() must be of the type string, null returned in /path/to/vendor/square/square/src/SquareClient.php:139
Stack trace:
#0 /path/to/vendor/square/square/src/Apis/LocationsApi.php(42): Square\SquareClient->getBaseUri()
#1 /path/to/admin/content/process_card.php(23): Square\Apis\LocationsApi->listLocations()
#2 /path/to/admin/index.php(151): include('/home/cprtocom/...')
#3 {main}
  thrown in /path/to/vendor/square/square/src/SquareClient.php on line 139
`
Any assistance in determining what I (or less likely the SDK) is doing wrong here would be greatly appreciated.
Thanks,
-Ray

**Comment by StephenJosey** [comment]
Have you already included the `Environment` (like `use Square\Environment;`)? I suspect the latter error is due to it not processing the environment correctly; I believe in the SDK code itself, it handles setting the base URI based on the environment, so if the Environment issue is resolved, the fatal error should be resolved, too. Let me know if that doesn't work, though.

**Comment by rsleventhal** [comment]
I have...my code shows this:

`$client = new SquareClient([
    'accessToken' => ACCESS_TOKEN,
    'environment' => $_SESSION['environment']
]);`

and output of a print_r() of $client produces this:

` [environment:Square\SquareClient:private] => Environment::SANDBOX,`

Thanks so much for your reply and assistance.  Much appreciated!

**Comment by StephenJosey** [comment]
Ah, it looks like maybe that it's passing as a string from the SESSION variable. For instance, when I `print_r` mine I see: `[environment:Square\SquareClient:private] => sandbox` (instead of `Environment::SANDBOX`). How are you setting the session variable for `environment`?

**Comment by rsleventhal** [comment]
I'm setting it manually, based on a static var in my libraries file.  That should be an easy fix then.  I will let you know.

Thanks again!

**Comment by rsleventhal** [comment]
Yup...that did the trick.  Can't tell you how much i appreciate your help!  

Best,
-R
