### ISSUE TITLE
Item's Unit Cost does not appear in CatalogObject

### ISSUE THREAD

**Issue by BarnumD** [square/square-php-sdk#41]
When pulling a CatalogObject (item) from the Square PHP API, the item's cost, as it appears in the GUI, is not included.

**Comment by StephenJosey** [comment]
Item/Unit cost is not currently available in the API. Further, anything specific to Square for Retail (or even Square for Restaurants) are not currently in the API. This is not a limitation of the SDK, but a limitation of the API, so I'll be closing this issue as it's a known feature request on our side. Let me know if you have any questions!
