### ISSUE TITLE
ExternalPaymentDetails api response may not include 'source' and throws exception.

### ISSUE THREAD

**Issue by seanbeach** [square/square-php-sdk#46]
I'm of the opinion that either
1. source should not be a required parameter if it won't always be sent
2. the api should never omit it in responses if it is a required value for the sdks

Removing this from the docblock has fixed my local issue for the time being.
https://github.com/square/square-php-sdk/blob/a1e88fc821bfa1099b07f4134db320959539b129/src/Models/ExternalPaymentDetails.php#L107
per [apimatic/jsonmapper readme topic](https://github.com/apimatic/jsonmapper#missing-properties)

**Comment by StephenJosey** [comment]
Hi Sean, do you have a `payment_id` where it's not present? Technically it is required, so if a payment is not returning it, that sounds like a bug to me, so I can pass it to the owning team to fix.

**Comment by seanbeach** [comment]
PaymentID: nyN8roNxjCJAIQQfalCrKQB

```
"external_details": {
    "type": "CARD"
 },
```

We have dozens of transactions that respond in this way.

**Comment by StephenJosey** [comment]
Thanks for sharing. I think I followed up on Slack, but didn't follow up here. To confirm, it sounds like this payment (and probably the others) are "other" payments taken well before Payments API supported it, and thus they do not have a source. Work is being done to add a source to these to prevent this exception from occurring.

**Comment by zenmasterjobo** [comment]
@StephenJosey  do you know if a fix for this has gone through?

**Comment by zenmasterjobo** [comment]
This has in fact been fixed, and exists on the payment now as `sourceType` https://github.com/square/square-php-sdk/blob/master/doc/models/payment.md

Please feel free to reopen if there are further questions!
