### ISSUE TITLE
Card Doc Link Missing

### ISSUE THREAD

**Issue by itsmemanoj** [square/square-php-sdk#60]
Hi,
Please fix the card link in the Payment Section.

Also, How to delete a customer card with a new Card API? There is only disable card method.

**Comment by wolfadex** [comment]
@itsmemanoj do you have a link to which Payment Section you're referring to? That would help me find the broken link a little faster.

For questions about APIs we recommend either asking in [our developer forums](https://developer.squareup.com/forums/), asking in [our developer Slack](https://buildwithsquare.slack.com/ssb/redirect), or [contacting developer support directly](https://squareup.com/help/us/en/contact?panel=BF53A9C8EF68).

**Comment by 123486A** [comment]
The link 'SDK Reference - Payments - Cards' on this page: https://github.com/square/square-php-sdk is broken. 

**Is:** https://github.com/square/square-php-sdk/blob/master/doc/api/cards.md
**Should be:** https://github.com/square/square-php-sdk/blob/master/doc/apis/cards.md

Missing the 's' in 'apis'

**Comment by zenmasterjobo** [comment]
Thanks for bringing to our attention @123486A.

This will be updated and fixed in our next SDK release.
