### ISSUE TITLE
Postal Code requires 5 characters in regions which do not have 5 characters.

### ISSUE THREAD

**Issue by turbo124** [square/square-php-sdk#63]
We are seeing an issue with users in Australia attempting to use this gateway. Square injects the postal code as a required field, but does not accept a 4 digit code (thats all we have in Australia).

The API also returns an ambiguous error message INVALID_CARD_DATA which causes some confusion.

https://github.com/invoiceninja/invoiceninja/issues/6729

**Comment by wolfadex** [comment]
@turbo124 which gateway are you referring to? Also, where are you seeing that a postal code is being required?

**Comment by amcdonald-4mentalhealth** [comment]
I'm seeing the same issue, I'm only using the sandbox mode at the moment, but will need to accept payments in £ when we go live and for customer data will be using their postcode for the CVS check which will be up to 8 characters

I'm using the CreatePayment function, in the PHP SDK  Payments API

At the moment it only allows a 5 number zip code which is presumably an American zip code of 5 numbers, ie no letters allowed so it will not accept UK postcodes containing letters and numbers, and usually over 5 digits

This is when the customers country is set to GB and the currency code set to GBP

**Comment by wolfadex** [comment]
@amcdonald-4mentalhealth thanks for the details! That's definitely an issue for many countries.

**Comment by zenmasterjobo** [comment]
Hi all, thanks for all of your feedback here,

I have confirmed that when trying to reproduce this issue with the latest php sdk that the issue seems to be resolved and I can take payments with non US zip codes. 

Cheers!
