### ISSUE TITLE
Uncaught Error: Class 'Square\SquareClient' not found

### ISSUE THREAD

**Issue by kufurex** [square/square-php-sdk#67]
I've checked and all the necessary files are being included with the following call:
require '/vendor/autoload.php';

I get the following error:
Uncaught Error: Class 'Square\SquareClient' not found...
...Stack trace: #0 {main} thrown

I think I have the correct code to get this working, but obviously something is going wrong.

use Square\SquareClient;
use Square\Environment;

$client = new SquareClient([
    'accessToken' => 'I-put-my-token-here',
    'environment' => Environment::SANDBOX,
]);

**Comment by kufurex** [comment]
I ended up installing it locally, instead of composer, and it worked fine.

**Comment by wolfadex** [comment]
I'm not very familiar with PHP yet, but have you checked out how we use the SDK in our examples, such as the [Payment Example](https://github.com/square/connect-api-examples/tree/master/connect-examples/v2/php_payment)?
