### ISSUE TITLE
No way to specify the integration ID

### ISSUE THREAD

**Issue by marchukvitaliy** [square/square-php-sdk#74]
You can find here https://github.com/square/connect-php-sdk/issues/94 previous issue where discussed the intergration of the "integration ID" in the charge request as integration_id is not present.
In the new API IntegrationChargeRequest has been replaced by CreatePaymentRequest but in it I still don't see integration for the "integration ID". Probably we should use setReferenceId() or setNote() but I don't think this is correct.
I also tried to inject a new parameter in CreatePaymentRequest:jsonSerialize() but in the request "POST /v2/payments" I don't see this parameter:
`{
  "source_id": "[redacted]",
  "idempotency_key": "621e56db0b7d62.20941928",
  "amount_money": {
    "amount": 2000,
    "currency": "USD"
  },
  "autocomplete": true,
  "order_id": "sdBPTC6oQ53XN3MaoShjCHmk6h4F",
  "buyer_email_address": "test@gmail.com",
  "billing_address": {
    "address_line_1": "test",
    "address_line_2": "",
    "locality": "test",
    "administrative_district_level_1": "",
    "postal_code": "",
    "country": ""
  }
}`
It looks like this parameter was removed somewhere on API side.
Is there a way to add a new parameter into CreatePaymentRequest:jsonSerialize() or do you plan to add it to the API ?

**Comment by wolfadex** [comment]
The SDKs themselves are generated from the APIs. If you have questions and/or concerns about the APIs I recommend reaching out on our [Forums](https://developer.squareup.com/forums/) or through [Slack](https://buildwithsquare.slack.com/ssb/redirect).
