### ISSUE TITLE
Op Cache can break response types, leading to a PHP Error

### ISSUE THREAD

**Issue by ziemkowski** [square/square-php-sdk#80]
We discovered an issue that would cause `ApiHelper::mapClass()` to return the correct class, but with properties using `stdClass` instead of the expected Square type, resulting in a PHP Error being thrown if the getter methods are invoked.

For example, when this issue is encountered, `CustomersApi->listCustomers()` [returns](https://github.com/square/square-php-sdk/blob/e41e5cc3ea98c1fa76fc69fe5d01586e09385078/src/Apis/CustomersApi.php#L116) a `ListCustomersResponse` instance via `ApiResponse->getResult()`, but `getCustomers()` returns an array of `stdClass` objects. This results in an error like `Call to undefined method stdClass::getId()` to be thrown when using any of the type's methods. All of the List models exhibit this behavior.

### Issue Details

[ApiHelper->mapClass()](https://github.com/square/square-php-sdk/blob/e41e5cc3ea98c1fa76fc69fe5d01586e09385078/src/ApiHelper.php#L119) uses [jsonmapper](https://github.com/apimatic/jsonmapper) to convert JSON response objects into the correct types. JsonMapper does this by using the Reflection API to get the phpDoc comments to infer the types. For example, by parsing `@var Customer[]|null` for [ListCustomersResponse->customers](https://github.com/square/square-php-sdk/blob/e41e5cc3ea98c1fa76fc69fe5d01586e09385078/src/Models/ListCustomersResponse.php#L23) to determine that it should instantiate an array of `Customer` objects.

The PHP Error we encountered was caused by phpDoc comments being ignored by the PHP Op Cache due to [`opcache.save_comments` ](https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.save-comments) being disabled in our PHP configuration. With that setting, JsonMapper can not determine the types of the properties so it leaves the `stdClass` instances originally returned by `json_decode()`.

### Requested Action

1. The PHP SDK documentation here should include a notice that it is incompatible with this configuration
2. The Square team should file a ticket against [JsonMapper](https://github.com/apimatic/jsonmapper/issues)
   1. Instantiating a mapper should throw a configuration exception if `opcache.save_comments` is set to off, similar to [Doctrine's `AnnotationException` checks](https://github.com/doctrine/annotations/blob/39f2a48113777ce9f5e02c04c5c1ba4ed80b9c3d/lib/Doctrine/Common/Annotations/AnnotationReader.php#L111-L120).

**Comment by wolfadex** [comment]
Thank you for reporting this. The SDK team is working on a fix.
