### ISSUE TITLE
Fatal Error for DELIVERY Orders

### ISSUE THREAD

**Issue by godsgood33** [square/square-php-sdk#84]
**Describe the bug**
Retrieving orders (either individual or all over a time frame) receive a fatal ApiException `DELIVERY is invalid for Square\Models\OrderFulfillmentType`.

```
PHP Fatal error:  Uncaught Square\Exceptions\ApiException: DELIVERY is invalid for Square\Models\OrderFulfillmentType. in /home/ryan/dev/workspace/gcj-analyzer/vendor/square/square/src/ApiHelper.php:123
Stack trace:
#0 /home/ryan/dev/workspace/gcj-analyzer/vendor/square/square/src/Apis/OrdersApi.php(453): Square\ApiHelper::mapClass()
#1 /home/ryan/dev/workspace/gcj-analyzer/src/Parsers/SquareParser.php(316): Square\Apis\OrdersApi->retrieveOrder()
#2 /home/ryan/dev/workspace/gcj-analyzer/bin/GetData.php(202): App\Parsers\SquareParser->retrieveOrder()
#3 {main}
  thrown in /home/ryan/dev/workspace/gcj-analyzer/vendor/square/square/src/ApiHelper.php on line 123
```

**Expected behavior**
No error
If I add a delivery public const just like the PICKUP and SHIPMENT that are already in the OrderFulfillmentType class and add it to the _ALL_TYPES array, it works just fine.

**To Reproduce**
I am using the searchOrders API to retrieve all orders over the day.  Below is my method.  `$startDate` and `$endDate` are passed into the method
```
$created_at = new TimeRange();
$created_at->setStartAt($startDate->format(DATE_RFC3339));
$created_at->setEndAt($endDate->format(DATE_RFC3339));

$date_time_filter = new SearchOrdersDateTimeFilter();
$date_time_filter->setCreatedAt($created_at);

$filter = new SearchOrdersFilter();
$filter->setDateTimeFilter($date_time_filter);

$query = new SearchOrdersQuery();
$query->setFilter($filter);

$body = new SearchOrdersRequest();
$body->setLocationIds(LOCATIONS);
$body->setQuery($query);

$this->api_response = $this->client->getOrdersApi()->searchOrders($body);

if (!$this->api_response->isSuccess()) {
    die($this->api_response->getErrors());
}
```

Running the same query on the API explorer returns the correct info because it looks like the error

**Square SDK version**
19.0.1.20220512

**Comment by wolfadex** [comment]
@godsgood33 sorry for the difficulties here. Coincidentally, we released a new version of the SDK just today. Would be able to upgrade and see if that resolved your issue?

**Comment by godsgood33** [comment]
@wolfadex I have not tried this, but I did look and the files are identical, so I don't think it will fix the issue.

**Comment by wolfadex** [comment]
Resolved by https://github.com/square/square-php-sdk/pull/86.

**Comment by wolfadex** [comment]
@godsgood33 please let us know if this is still an issue after this release, or if there are any other issues you encounter.

**Comment by godsgood33** [comment]
@wolfadex I'll update in the next couple days

**Comment by godsgood33** [comment]
Not seeing the error anymore.  Thanks!
