### ISSUE TITLE
unirest-php has removed static entities in the latest release

### ISSUE THREAD

**Issue by AjSleigh** [square/square-php-sdk#90]
**Describe the bug**
The latest release of [unirest-php](https://github.com/apimatic/unirest-php) has removed static entities causing fatal php errors starting with BaseApi.php line 63.

**Expected behavior**
The sample code to work.

**To Reproduce**
Steps to reproduce the bug:
1. Follow the instructions for manual configuration
2. use unirest-php-3.0.0 (the latest version)
3. The code fails
4. use unirest-php-2.3.0
5. The code works

**Square SDK version**
square-php-sdk-20.1.0.20220720

**Additional context**

**Comment by zenmasterjobo** [comment]
Hey @AjSleigh,

Are you still experiencing this issue? I can't seem to be able to reproduce your issue using the latest version of the PHP SDK (25.2.0.20230315).

**Comment by AjSleigh** [comment]
No, I think this was fixed shortly after I reported it.
